// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCza7HqBAVh2w0-FzLYSAqadTmbVrEguaU',
    appId: '1:788104912338:web:6ec0f9b7b3d007f3d1fc0b',
    messagingSenderId: '788104912338',
    projectId: 'chat-app-21eb7',
    authDomain: 'chat-app-21eb7.firebaseapp.com',
    storageBucket: 'chat-app-21eb7.appspot.com',
    measurementId: 'G-M9XE1D2TQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFej13nP_-RM8nYetOGFoaa2s8-amUV7k',
    appId: '1:788104912338:android:6c1e10d235164cdfd1fc0b',
    messagingSenderId: '788104912338',
    projectId: 'chat-app-21eb7',
    storageBucket: 'chat-app-21eb7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJJxdjr0FGgZel2s5MDLJnEt_6XSNjLQY',
    appId: '1:788104912338:ios:e40072e396152dfbd1fc0b',
    messagingSenderId: '788104912338',
    projectId: 'chat-app-21eb7',
    storageBucket: 'chat-app-21eb7.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJJxdjr0FGgZel2s5MDLJnEt_6XSNjLQY',
    appId: '1:788104912338:ios:e40072e396152dfbd1fc0b',
    messagingSenderId: '788104912338',
    projectId: 'chat-app-21eb7',
    storageBucket: 'chat-app-21eb7.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCza7HqBAVh2w0-FzLYSAqadTmbVrEguaU',
    appId: '1:788104912338:web:7012b034d5c680e1d1fc0b',
    messagingSenderId: '788104912338',
    projectId: 'chat-app-21eb7',
    authDomain: 'chat-app-21eb7.firebaseapp.com',
    storageBucket: 'chat-app-21eb7.appspot.com',
    measurementId: 'G-YYC2L7HRCF',
  );
}
